"""empty message

Revision ID: b03df4921c3c
Revises: bdcb6f5eff28
Create Date: 2019-09-20 16:10:43.675057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b03df4921c3c'
down_revision = 'bdcb6f5eff28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('b_category',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cg_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cg_name')
    )
    op.create_table('b_posts',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_title', sa.String(length=256), nullable=False),
    sa.Column('post_digest', sa.String(length=512), nullable=False),
    sa.Column('post_content', sa.Text(), nullable=False),
    sa.Column('post_clicks', sa.Integer(), nullable=True),
    sa.Column('post_like_num', sa.Integer(), nullable=True),
    sa.Column('post_index_image_url', sa.String(length=256), nullable=True),
    sa.Column('post_status', sa.Integer(), nullable=True),
    sa.Column('post_can_comment', sa.Integer(), nullable=True),
    sa.Column('post_category_id', sa.Integer(), nullable=False),
    sa.Column('post_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_category_id'], ['b_category.id'], ),
    sa.ForeignKeyConstraint(['post_user_id'], ['b_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('b_comments',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_user_id', sa.Integer(), nullable=False),
    sa.Column('comment_content', sa.Text(), nullable=False),
    sa.Column('comment_from_admin', sa.Integer(), nullable=True),
    sa.Column('comment_status', sa.Integer(), nullable=True),
    sa.Column('comment_post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_post_id'], ['b_posts.id'], ),
    sa.ForeignKeyConstraint(['comment_user_id'], ['b_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('b_reply',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reply_from_user', sa.Integer(), nullable=False),
    sa.Column('reply_to_user', sa.Integer(), nullable=False),
    sa.Column('reply_content', sa.Text(), nullable=False),
    sa.Column('reply_comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reply_comment_id'], ['b_comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('b_reply')
    op.drop_table('b_comments')
    op.drop_table('b_posts')
    op.drop_table('b_category')
    # ### end Alembic commands ###
