"""empty message

Revision ID: bdcb6f5eff28
Revises: d6942e368ba3
Create Date: 2019-09-19 16:11:50.748734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdcb6f5eff28'
down_revision = 'd6942e368ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('b_users', sa.Column('desc', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('b_users', 'desc')
    # ### end Alembic commands ###
