"""empty message

Revision ID: d40faa0baadd
Revises: b03df4921c3c
Create Date: 2019-09-20 16:21:10.521789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd40faa0baadd'
down_revision = 'b03df4921c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('b_comments_ibfk_2', 'b_comments', type_='foreignkey')
    op.alter_column('b_posts', 'post_user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint('b_posts_ibfk_2', 'b_posts', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('b_posts_ibfk_2', 'b_posts', 'b_users', ['post_user_id'], ['id'])
    op.alter_column('b_posts', 'post_user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key('b_comments_ibfk_2', 'b_comments', 'b_users', ['comment_user_id'], ['id'])
    # ### end Alembic commands ###
