"""empty message

Revision ID: d6942e368ba3
Revises: 6b1a97070f70
Create Date: 2019-09-19 15:33:47.553396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6942e368ba3'
down_revision = '6b1a97070f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('b_users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'b_users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'b_users', type_='unique')
    op.drop_column('b_users', 'email')
    # ### end Alembic commands ###
